name: Build Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ..
          
      - name: Skip Electron native rebuild
        run: |
          echo "Skipping native rebuild, using prebuilt binaries"

      - name: Run tests (if available)
        run: |
          # npm test
          echo "Tests would run here"

      - name: Build frontend
        run: |
          cd frontend && npm run build

      - name: Test Electron packaging (using electron-builder)
        run: |
          npx electron-builder@24.13.3 --win portable --dir
        env:
          NODE_ENV: production
          CSC_IDENTITY_AUTO_DISCOVERY: false
